---
- name: DX Development Environment Setup
  hosts: localhost
  connection: local
  
  vars:
    vscode_extensions:
      - bradlc.vscode-tailwindcss
      - vivaxy.vscode-conventional-commits
      - JakeBecker.elixir-ls
      - usernamehw.errorlens
      - dbaeumer.vscode-eslint
      - Gxl.git-graph-3
      - eamodio.gitlens
      - golang.go
      - bbenoist.Nix
      - antfu.goto-alias
      - CraigRBroughton.htmx-attributes
      - afzalsayed96.icones
      - antfu.iconify
      - MariusAlchimavicius.json-to-ts
      - CraigRBroughton.modern-vue-snippets
      - antfu.pnpm-catalog-lens
      - boydmeyer.pop-dark
      - YoavBls.pretty-ts-errors
      - Orta.vscode-twoslash-queries
      - antfu.unocss
      - antfu.theme-vitesse
      - Vue.volar
      - ziglang.vscode-zig
      - Catppuccin.catppuccin-vsc-icons
      - vscode-icons-team.vscode-icons
      - oven.bun-vscode
      - adpyke.codesnap
      - formulahendry.auto-rename-tag
      
  
  tasks:
    - name: "Install VSCode extensions"
      shell: "code --install-extension {{ item }}"
      loop: "{{ vscode_extensions }}"
      register: extension_results
      failed_when: extension_results.rc != 0 and "already installed" not in extension_results.stderr
      changed_when: "'successfully installed' in extension_results.stdout"
      
    - name: "Setup Summary"
      debug:
        msg: "VSCode extensions installed successfully!"